/*==============================================================*/
/* El Retazo Market - Secuencias para claves primarias simples  */
/* Diseñado para ejecutarse sobre una base de datos ya creada.  */
/* PostgreSQL                                                   */
/*==============================================================*/

BEGIN;

-- Evita inserciones concurrentes mientras las secuencias se sincronizan
-- con los identificadores que ya existen en las tablas.
LOCK TABLE
    AUDITORIA,
    CAT_MAT,
    CLIENTE,
    ENVIO,
    FACTURAS,
    IMAGENES,
    LINEAS,
    MATERIALES,
    METODO_PAGO,
    MOV_MATERIALES,
    MOV_PRODUCTOS,
    PEDIDOS,
    PERSONALIZACION,
    PRODUCTOS,
    PROVEEDORES,
    ROL,
    USUARIO
IN SHARE ROW EXCLUSIVE MODE;

CREATE SEQUENCE IF NOT EXISTS SEQ_AUDITORIA_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CAT_MAT_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CLIENTE_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ENVIO_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_FACTURAS_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_IMAGENES_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_LINEAS_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_MATERIALES_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_METODO_PAGO_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_MOV_MATERIALES_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_MOV_PRODUCTOS_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PEDIDOS_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PERSONALIZACION_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PRODUCTOS_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PROVEEDORES_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ROL_ID AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_USUARIO_ID AS INT START WITH 1 INCREMENT BY 1;

-- Cada secuencia queda vinculada a la columna que genera.
ALTER SEQUENCE SEQ_AUDITORIA_ID OWNED BY AUDITORIA.ID_AUDITORIA;
ALTER SEQUENCE SEQ_CAT_MAT_ID OWNED BY CAT_MAT.ID_CATEGORIA;
ALTER SEQUENCE SEQ_CLIENTE_ID OWNED BY CLIENTE.ID_CLIENTE;
ALTER SEQUENCE SEQ_ENVIO_ID OWNED BY ENVIO.ID_ENVIO;
ALTER SEQUENCE SEQ_FACTURAS_ID OWNED BY FACTURAS.ID_FACTURA;
ALTER SEQUENCE SEQ_IMAGENES_ID OWNED BY IMAGENES.ID_IMAGEN;
ALTER SEQUENCE SEQ_LINEAS_ID OWNED BY LINEAS.ID_LINEA;
ALTER SEQUENCE SEQ_MATERIALES_ID OWNED BY MATERIALES.ID_MATERIAL;
ALTER SEQUENCE SEQ_METODO_PAGO_ID OWNED BY METODO_PAGO.ID_METODO;
ALTER SEQUENCE SEQ_MOV_MATERIALES_ID OWNED BY MOV_MATERIALES.ID_MOVIMIENTO;
ALTER SEQUENCE SEQ_MOV_PRODUCTOS_ID OWNED BY MOV_PRODUCTOS.ID_MOVIMIENTO2;
ALTER SEQUENCE SEQ_PEDIDOS_ID OWNED BY PEDIDOS.ID_PEDIDO;
ALTER SEQUENCE SEQ_PERSONALIZACION_ID OWNED BY PERSONALIZACION.ID_OPCION;
ALTER SEQUENCE SEQ_PRODUCTOS_ID OWNED BY PRODUCTOS.ID_PRODUCTO;
ALTER SEQUENCE SEQ_PROVEEDORES_ID OWNED BY PROVEEDORES.ID_PROVEEDOR;
ALTER SEQUENCE SEQ_ROL_ID OWNED BY ROL.ID_ROL;
ALTER SEQUENCE SEQ_USUARIO_ID OWNED BY USUARIO.ID_USUARIO;

-- Permite que PostgreSQL genere el ID cuando el INSERT omite la columna.
ALTER TABLE AUDITORIA ALTER COLUMN ID_AUDITORIA SET DEFAULT nextval('SEQ_AUDITORIA_ID');
ALTER TABLE CAT_MAT ALTER COLUMN ID_CATEGORIA SET DEFAULT nextval('SEQ_CAT_MAT_ID');
ALTER TABLE CLIENTE ALTER COLUMN ID_CLIENTE SET DEFAULT nextval('SEQ_CLIENTE_ID');
ALTER TABLE ENVIO ALTER COLUMN ID_ENVIO SET DEFAULT nextval('SEQ_ENVIO_ID');
ALTER TABLE FACTURAS ALTER COLUMN ID_FACTURA SET DEFAULT nextval('SEQ_FACTURAS_ID');
ALTER TABLE IMAGENES ALTER COLUMN ID_IMAGEN SET DEFAULT nextval('SEQ_IMAGENES_ID');
ALTER TABLE LINEAS ALTER COLUMN ID_LINEA SET DEFAULT nextval('SEQ_LINEAS_ID');
ALTER TABLE MATERIALES ALTER COLUMN ID_MATERIAL SET DEFAULT nextval('SEQ_MATERIALES_ID');
ALTER TABLE METODO_PAGO ALTER COLUMN ID_METODO SET DEFAULT nextval('SEQ_METODO_PAGO_ID');
ALTER TABLE MOV_MATERIALES ALTER COLUMN ID_MOVIMIENTO SET DEFAULT nextval('SEQ_MOV_MATERIALES_ID');
ALTER TABLE MOV_PRODUCTOS ALTER COLUMN ID_MOVIMIENTO2 SET DEFAULT nextval('SEQ_MOV_PRODUCTOS_ID');
ALTER TABLE PEDIDOS ALTER COLUMN ID_PEDIDO SET DEFAULT nextval('SEQ_PEDIDOS_ID');
ALTER TABLE PERSONALIZACION ALTER COLUMN ID_OPCION SET DEFAULT nextval('SEQ_PERSONALIZACION_ID');
ALTER TABLE PRODUCTOS ALTER COLUMN ID_PRODUCTO SET DEFAULT nextval('SEQ_PRODUCTOS_ID');
ALTER TABLE PROVEEDORES ALTER COLUMN ID_PROVEEDOR SET DEFAULT nextval('SEQ_PROVEEDORES_ID');
ALTER TABLE ROL ALTER COLUMN ID_ROL SET DEFAULT nextval('SEQ_ROL_ID');
ALTER TABLE USUARIO ALTER COLUMN ID_USUARIO SET DEFAULT nextval('SEQ_USUARIO_ID');

-- Coloca cada secuencia en el siguiente valor libre. El tercer parámetro en
-- FALSE hace que el próximo nextval() devuelva exactamente MAX(ID) + 1.
SELECT setval('SEQ_AUDITORIA_ID', COALESCE((SELECT MAX(ID_AUDITORIA) FROM AUDITORIA), 0) + 1, FALSE);
SELECT setval('SEQ_CAT_MAT_ID', COALESCE((SELECT MAX(ID_CATEGORIA) FROM CAT_MAT), 0) + 1, FALSE);
SELECT setval('SEQ_CLIENTE_ID', COALESCE((SELECT MAX(ID_CLIENTE) FROM CLIENTE), 0) + 1, FALSE);
SELECT setval('SEQ_ENVIO_ID', COALESCE((SELECT MAX(ID_ENVIO) FROM ENVIO), 0) + 1, FALSE);
SELECT setval('SEQ_FACTURAS_ID', COALESCE((SELECT MAX(ID_FACTURA) FROM FACTURAS), 0) + 1, FALSE);
SELECT setval('SEQ_IMAGENES_ID', COALESCE((SELECT MAX(ID_IMAGEN) FROM IMAGENES), 0) + 1, FALSE);
SELECT setval('SEQ_LINEAS_ID', COALESCE((SELECT MAX(ID_LINEA) FROM LINEAS), 0) + 1, FALSE);
SELECT setval('SEQ_MATERIALES_ID', COALESCE((SELECT MAX(ID_MATERIAL) FROM MATERIALES), 0) + 1, FALSE);
SELECT setval('SEQ_METODO_PAGO_ID', COALESCE((SELECT MAX(ID_METODO) FROM METODO_PAGO), 0) + 1, FALSE);
SELECT setval('SEQ_MOV_MATERIALES_ID', COALESCE((SELECT MAX(ID_MOVIMIENTO) FROM MOV_MATERIALES), 0) + 1, FALSE);
SELECT setval('SEQ_MOV_PRODUCTOS_ID', COALESCE((SELECT MAX(ID_MOVIMIENTO2) FROM MOV_PRODUCTOS), 0) + 1, FALSE);
SELECT setval('SEQ_PEDIDOS_ID', COALESCE((SELECT MAX(ID_PEDIDO) FROM PEDIDOS), 0) + 1, FALSE);
SELECT setval('SEQ_PERSONALIZACION_ID', COALESCE((SELECT MAX(ID_OPCION) FROM PERSONALIZACION), 0) + 1, FALSE);
SELECT setval('SEQ_PRODUCTOS_ID', COALESCE((SELECT MAX(ID_PRODUCTO) FROM PRODUCTOS), 0) + 1, FALSE);
SELECT setval('SEQ_PROVEEDORES_ID', COALESCE((SELECT MAX(ID_PROVEEDOR) FROM PROVEEDORES), 0) + 1, FALSE);
SELECT setval('SEQ_ROL_ID', COALESCE((SELECT MAX(ID_ROL) FROM ROL), 0) + 1, FALSE);
SELECT setval('SEQ_USUARIO_ID', COALESCE((SELECT MAX(ID_USUARIO) FROM USUARIO), 0) + 1, FALSE);

COMMIT;

