using Asp.Versioning;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Servicio.RetazoMarket.Api.Extensions;using Servicio.RetazoMarket.Api.Models.Common;using Servicio.RetazoMarket.Business.DTOs.Descuento;using Servicio.RetazoMarket.Business.Exceptions;using Servicio.RetazoMarket.Business.Interfaces;using Servicio.RetazoMarket.DataManagment.Models.Common;
namespace Servicio.RetazoMarket.Api.Controllers.V1.Internal.Catalogo;
[ApiController][ApiVersion("1.0")][Authorize(Policy=AuthorizationExtensions.AdministradorPolicy)][Route("api/v{version:apiVersion}/internal/descuentos")][ProducesResponseType(typeof(ApiErrorResponse),400)][ProducesResponseType(typeof(ApiErrorResponse),401)][ProducesResponseType(typeof(ApiErrorResponse),403)][ProducesResponseType(typeof(ApiErrorResponse),404)]
public class DescuentosController:ControllerBase{private readonly IDescuentoService _s;public DescuentosController(IDescuentoService s)=>_s=s;
[HttpGet]public async Task<IActionResult> Todos(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<DescuentoResponse>>.Ok(await _s.ObtenerTodosAsync(ct)));
[HttpGet("{id:int}")]public async Task<IActionResult> PorId(int id,CancellationToken ct)=>Ok(ApiResponse<DescuentoResponse>.Ok(await _s.ObtenerPorIdAsync(id,ct)??throw new NotFoundException("El descuento no existe.")));
[HttpGet("producto/{id:int}")]public async Task<IActionResult> PorProducto(int id,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<DescuentoResponse>>.Ok(await _s.ObtenerPorProductoAsync(id,ct)));
[HttpGet("buscar")]public async Task<IActionResult> Buscar([FromQuery]DescuentoFiltroRequest f,CancellationToken ct)=>Ok(ApiResponse<DataPagedResult<DescuentoResponse>>.Ok(await _s.BuscarAsync(f,ct)));
[HttpPost]public async Task<IActionResult> Crear([FromBody]CrearDescuentoRequest r,CancellationToken ct){var x=await _s.CrearAsync(r,ct);return CreatedAtAction(nameof(PorId),new{version="1.0",id=x.id_descuento},ApiResponse<DescuentoResponse>.Ok(x,"Descuento creado exitosamente."));}
[HttpPut("{id:int}")]public async Task<IActionResult> Actualizar(int id,[FromBody]ActualizarDescuentoRequest r,CancellationToken ct){r.id_descuento=id;return Ok(ApiResponse<DescuentoResponse>.Ok(await _s.ActualizarAsync(r,ct)??throw new NotFoundException("El descuento no existe.")));}
[HttpPost("{id:int}/inactivar")]public async Task<IActionResult> Inactivar(int id,CancellationToken ct){if(!await _s.InactivarAsync(id,ct))throw new NotFoundException("El descuento no existe.");return Ok(ApiResponse<bool>.Ok(true,"Descuento inactivado."));}
[HttpGet("producto/{idProducto:int}/calcular")]public async Task<IActionResult> Calcular(int idProducto,[FromQuery]int cantidad,[FromQuery]decimal subtotal,CancellationToken ct)=>Ok(ApiResponse<DescuentoAplicadoResponse>.Ok(await _s.CalcularAplicableAsync(idProducto,cantidad,subtotal,ct)));}
