using Asp.Versioning;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Servicio.RetazoMarket.Api.Extensions;using Servicio.RetazoMarket.Api.Models.Common;using Servicio.RetazoMarket.Business.DTOs.Material;using Servicio.RetazoMarket.Business.Exceptions;using Servicio.RetazoMarket.Business.Interfaces;using Servicio.RetazoMarket.DataManagment.Models.Common;
namespace Servicio.RetazoMarket.Api.Controllers.V1.Internal.Catalogo;
[ApiController][ApiVersion("1.0")][Authorize(Policy=AuthorizationExtensions.AdministradorPolicy)][Route("api/v{version:apiVersion}/internal/materiales")][ProducesResponseType(typeof(ApiErrorResponse),400)][ProducesResponseType(typeof(ApiErrorResponse),401)][ProducesResponseType(typeof(ApiErrorResponse),403)][ProducesResponseType(typeof(ApiErrorResponse),404)]
public class MaterialesController:ControllerBase{private readonly IMaterialService _s;public MaterialesController(IMaterialService s)=>_s=s;
[HttpGet]public async Task<IActionResult> Todos(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<MaterialResponse>>.Ok(await _s.ObtenerTodosAsync(ct)));
[HttpGet("{id:int}")]public async Task<IActionResult> PorId(int id,CancellationToken ct)=>Ok(ApiResponse<MaterialResponse>.Ok(await _s.ObtenerPorIdAsync(id,ct)??throw new NotFoundException("El material no existe.")));
[HttpGet("nombre/{nombre}")]public async Task<IActionResult> PorNombre(string nombre,CancellationToken ct)=>Ok(ApiResponse<MaterialResponse>.Ok(await _s.ObtenerPorNombreAsync(nombre,ct)??throw new NotFoundException("El material no existe.")));
[HttpGet("buscar")]public async Task<IActionResult> Buscar([FromQuery]MaterialFiltroRequest f,CancellationToken ct)=>Ok(ApiResponse<DataPagedResult<MaterialResponse>>.Ok(await _s.BuscarAsync(f,ct)));
[HttpPost]public async Task<IActionResult> Crear([FromBody]CrearMaterialRequest r,CancellationToken ct){var x=await _s.CrearAsync(r,ct);return CreatedAtAction(nameof(PorId),new{version="1.0",id=x.id_material},ApiResponse<MaterialResponse>.Ok(x,"Material creado exitosamente."));}
[HttpPut("{id:int}")]public async Task<IActionResult> Actualizar(int id,[FromBody]ActualizarMaterialRequest r,CancellationToken ct){r.id_material=id;return Ok(ApiResponse<MaterialResponse>.Ok(await _s.ActualizarAsync(r,ct)??throw new NotFoundException("El material no existe.")));}
[HttpDelete("{id:int}")]public async Task<IActionResult> Eliminar(int id,CancellationToken ct){if(!await _s.EliminarAsync(id,ct))throw new NotFoundException("El material no existe.");return Ok(ApiResponse<bool>.Ok(true,"Material eliminado lógicamente."));}}
