using Asp.Versioning;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Servicio.RetazoMarket.Api.Extensions;using Servicio.RetazoMarket.Api.Models.Common;using Servicio.RetazoMarket.Business.DTOs.Producto;using Servicio.RetazoMarket.Business.Exceptions;using Servicio.RetazoMarket.Business.Interfaces;using Servicio.RetazoMarket.DataManagment.Models.Common;
namespace Servicio.RetazoMarket.Api.Controllers.V1.Internal.Catalogo;
[ApiController][ApiVersion("1.0")][Authorize(Policy=AuthorizationExtensions.AdministradorPolicy)][Route("api/v{version:apiVersion}/internal/productos")][ProducesResponseType(typeof(ApiErrorResponse),400)][ProducesResponseType(typeof(ApiErrorResponse),401)][ProducesResponseType(typeof(ApiErrorResponse),403)][ProducesResponseType(typeof(ApiErrorResponse),404)]
public class ProductosController:ControllerBase{private readonly IProductoService _s;public ProductosController(IProductoService s)=>_s=s;
[HttpGet]public async Task<IActionResult> Todos(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<ProductoResponse>>.Ok(await _s.ObtenerTodosAsync(ct)));
[HttpGet("{id:int}")]public async Task<IActionResult> PorId(int id,CancellationToken ct)=>Ok(ApiResponse<ProductoResponse>.Ok(await _s.ObtenerPorIdAsync(id,ct)??throw new NotFoundException("El producto no existe.")));
[HttpGet("nombre/{nombre}")]public async Task<IActionResult> PorNombre(string nombre,CancellationToken ct)=>Ok(ApiResponse<ProductoResponse>.Ok(await _s.ObtenerPorNombreAsync(nombre,ct)??throw new NotFoundException("El producto no existe.")));
[HttpGet("buscar")]public async Task<IActionResult> Buscar([FromQuery]ProductoFiltroRequest f,CancellationToken ct)=>Ok(ApiResponse<DataPagedResult<ProductoResponse>>.Ok(await _s.BuscarAsync(f,ct)));
[HttpPost]public async Task<IActionResult> Crear([FromBody]CrearProductoRequest r,CancellationToken ct){var x=await _s.CrearAsync(r,ct);return CreatedAtAction(nameof(PorId),new{version="1.0",id=x.id_producto},ApiResponse<ProductoResponse>.Ok(x,"Producto creado exitosamente."));}
[HttpPut("{id:int}")]public async Task<IActionResult> Actualizar(int id,[FromBody]ActualizarProductoRequest r,CancellationToken ct){r.id_producto=id;return Ok(ApiResponse<ProductoResponse>.Ok(await _s.ActualizarAsync(r,ct)??throw new NotFoundException("El producto no existe.")));}
[HttpDelete("{id:int}")]public async Task<IActionResult> Eliminar(int id,CancellationToken ct){if(!await _s.EliminarAsync(id,ct))throw new NotFoundException("El producto no existe.");return Ok(ApiResponse<bool>.Ok(true,"Producto eliminado lógicamente."));}
[HttpPost("fabricacion")]public async Task<IActionResult> Fabricar([FromBody]RegistrarProductoFabricadoRequest r,CancellationToken ct){var x=await _s.RegistrarFabricacionAsync(r,ct);return CreatedAtAction(nameof(PorId),new{version="1.0",id=x.id_producto},ApiResponse<ProductoResponse>.Ok(x,"Fabricación registrada exitosamente."));}}
