using Asp.Versioning;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Servicio.RetazoMarket.Api.Extensions;using Servicio.RetazoMarket.Api.Models.Common;using Servicio.RetazoMarket.Business.DTOs.ProveedorMaterial;using Servicio.RetazoMarket.Business.Exceptions;using Servicio.RetazoMarket.Business.Interfaces;
namespace Servicio.RetazoMarket.Api.Controllers.V1.Internal.Catalogo;
[ApiController][ApiVersion("1.0")][Authorize(Policy=AuthorizationExtensions.AdministradorPolicy)][Route("api/v{version:apiVersion}/internal/proveedores-materiales")][ProducesResponseType(typeof(ApiErrorResponse),400)][ProducesResponseType(typeof(ApiErrorResponse),401)][ProducesResponseType(typeof(ApiErrorResponse),403)][ProducesResponseType(typeof(ApiErrorResponse),404)]
public class ProveedoresMaterialesController:ControllerBase{private readonly IProveedorMaterialService _s;public ProveedoresMaterialesController(IProveedorMaterialService s)=>_s=s;
[HttpGet("material/{idMaterial:int}/proveedor/{idProveedor:int}")]public async Task<IActionResult> Obtener(int idMaterial,int idProveedor,CancellationToken ct)=>Ok(ApiResponse<ProveedorMaterialResponse>.Ok(await _s.ObtenerAsync(idMaterial,idProveedor,ct)??throw new NotFoundException("La relación proveedor-material no existe.")));
[HttpGet("proveedor/{id:int}")]public async Task<IActionResult> PorProveedor(int id,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<ProveedorMaterialResponse>>.Ok(await _s.ObtenerPorProveedorAsync(id,ct)));
[HttpGet("material/{id:int}")]public async Task<IActionResult> PorMaterial(int id,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<ProveedorMaterialResponse>>.Ok(await _s.ObtenerPorMaterialAsync(id,ct)));
[HttpPost]public async Task<IActionResult> Crear([FromBody]CrearProveedorMaterialRequest r,CancellationToken ct){var x=await _s.CrearAsync(r,ct);return CreatedAtAction(nameof(Obtener),new{version="1.0",idMaterial=x.id_material,idProveedor=x.id_proveedor},ApiResponse<ProveedorMaterialResponse>.Ok(x,"Relación creada exitosamente."));}
[HttpPut("material/{idMaterial:int}/proveedor/{idProveedor:int}")]public async Task<IActionResult> Actualizar(int idMaterial,int idProveedor,[FromBody]ActualizarProveedorMaterialRequest r,CancellationToken ct){r.id_material=idMaterial;r.id_proveedor=idProveedor;return Ok(ApiResponse<ProveedorMaterialResponse>.Ok(await _s.ActualizarAsync(r,ct)??throw new NotFoundException("La relación proveedor-material no existe.")));}}
