using Asp.Versioning;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Servicio.RetazoMarket.Api.Extensions;using Servicio.RetazoMarket.Api.Models.Common;using Servicio.RetazoMarket.Business.DTOs.Proveedor;using Servicio.RetazoMarket.Business.Exceptions;using Servicio.RetazoMarket.Business.Interfaces;using Servicio.RetazoMarket.DataManagment.Models.Common;
namespace Servicio.RetazoMarket.Api.Controllers.V1.Internal.Catalogo;
[ApiController][ApiVersion("1.0")][Authorize(Policy=AuthorizationExtensions.AdministradorPolicy)][Route("api/v{version:apiVersion}/internal/proveedores")][ProducesResponseType(typeof(ApiErrorResponse),400)][ProducesResponseType(typeof(ApiErrorResponse),401)][ProducesResponseType(typeof(ApiErrorResponse),403)][ProducesResponseType(typeof(ApiErrorResponse),404)]
public class ProveedoresController:ControllerBase{private readonly IProveedorService _s;public ProveedoresController(IProveedorService s)=>_s=s;
[HttpGet]public async Task<IActionResult> Todos(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<ProveedorResponse>>.Ok(await _s.ObtenerTodosAsync(ct)));
[HttpGet("{id:int}")]public async Task<IActionResult> PorId(int id,CancellationToken ct)=>Ok(ApiResponse<ProveedorResponse>.Ok(await _s.ObtenerPorIdAsync(id,ct)??throw new NotFoundException("El proveedor no existe.")));
[HttpGet("codigo/{codigo}")]public async Task<IActionResult> PorCodigo(string codigo,CancellationToken ct)=>Ok(ApiResponse<ProveedorResponse>.Ok(await _s.ObtenerPorCodigoAsync(codigo,ct)??throw new NotFoundException("El proveedor no existe.")));
[HttpGet("correo/{correo}")]public async Task<IActionResult> PorCorreo(string correo,CancellationToken ct)=>Ok(ApiResponse<ProveedorResponse>.Ok(await _s.ObtenerPorCorreoAsync(correo,ct)??throw new NotFoundException("El proveedor no existe.")));
[HttpGet("buscar")]public async Task<IActionResult> Buscar([FromQuery]ProveedorFiltroRequest f,CancellationToken ct)=>Ok(ApiResponse<DataPagedResult<ProveedorResponse>>.Ok(await _s.BuscarAsync(f,ct)));
[HttpPost]public async Task<IActionResult> Crear([FromBody]CrearProveedorRequest r,CancellationToken ct){var x=await _s.CrearAsync(r,ct);return CreatedAtAction(nameof(PorId),new{version="1.0",id=x.id_proveedor},ApiResponse<ProveedorResponse>.Ok(x,"Proveedor creado exitosamente."));}
[HttpPut("{id:int}")]public async Task<IActionResult> Actualizar(int id,[FromBody]ActualizarProveedorRequest r,CancellationToken ct){r.id_proveedor=id;return Ok(ApiResponse<ProveedorResponse>.Ok(await _s.ActualizarAsync(r,ct)??throw new NotFoundException("El proveedor no existe.")));}
[HttpDelete("{id:int}")]public async Task<IActionResult> Eliminar(int id,CancellationToken ct){if(!await _s.EliminarAsync(id,ct))throw new NotFoundException("El proveedor no existe.");return Ok(ApiResponse<bool>.Ok(true,"Proveedor eliminado lógicamente."));}}
