using Asp.Versioning;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Servicio.RetazoMarket.Api.Extensions;using Servicio.RetazoMarket.Api.Models.Common;using Servicio.RetazoMarket.Business.DTOs.Pedido;using Servicio.RetazoMarket.Business.Exceptions;using Servicio.RetazoMarket.Business.Interfaces;using Servicio.RetazoMarket.DataManagment.Models.Common;
namespace Servicio.RetazoMarket.Api.Controllers.V1.Internal.Comercial;
[ApiController][ApiVersion("1.0")][Authorize(Policy=AuthorizationExtensions.AdministradorPolicy)][Route("api/v{version:apiVersion}/internal/pedidos")][ProducesResponseType(typeof(ApiErrorResponse),400)][ProducesResponseType(typeof(ApiErrorResponse),401)][ProducesResponseType(typeof(ApiErrorResponse),403)][ProducesResponseType(typeof(ApiErrorResponse),404)]
public class PedidosController:ControllerBase{private readonly IPedidoService _s;public PedidosController(IPedidoService s)=>_s=s;
[HttpGet]public async Task<IActionResult> Todos(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<PedidoResponse>>.Ok(await _s.ObtenerTodosAsync(ct)));
[HttpGet("{id:int}")]public async Task<IActionResult> PorId(int id,CancellationToken ct)=>Ok(ApiResponse<PedidoResponse>.Ok(await _s.ObtenerPorIdAsync(id,ct)??throw new NotFoundException("El pedido no existe.")));
[HttpGet("buscar")]public async Task<IActionResult> Buscar([FromQuery]PedidoFiltroRequest f,CancellationToken ct)=>Ok(ApiResponse<DataPagedResult<PedidoResponse>>.Ok(await _s.BuscarAsync(f,ct)));
[HttpPost]public async Task<IActionResult> Crear([FromBody]CrearPedidoRequest r,CancellationToken ct){var x=await _s.CrearAsync(r,ct);return CreatedAtAction(nameof(PorId),new{version="1.0",id=x.id_pedido},ApiResponse<PedidoResponse>.Ok(x,"Pedido creado exitosamente."));}
[HttpPut("{id:int}")]public async Task<IActionResult> Actualizar(int id,[FromBody]ActualizarPedidoRequest r,CancellationToken ct){r.id_pedido=id;return Ok(ApiResponse<PedidoResponse>.Ok(await _s.ActualizarAsync(r,ct)??throw new NotFoundException("El pedido no existe.")));}
[HttpPost("{id:int}/pagar")]public async Task<IActionResult> Pagar(int id,CancellationToken ct)=>Ok(ApiResponse<PagoSimuladoResponse>.Ok(await _s.PagarAsync(id,ct),"Pago simulado procesado exitosamente."));}
